// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemAnalysis1.Models;

#nullable disable

namespace ProblemAnalysis1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250216231430_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ProblemAnalysis1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentSchoolNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateofBirth = "1971-05-31",
                            FirstName = "Bart",
                            GPA = 2.7f,
                            LastName = "Simpson",
                            StudentSchoolNumber = 87654321
                        },
                        new
                        {
                            Id = 2,
                            DateofBirth = "1973-08-05",
                            FirstName = "Lisa",
                            GPA = 2.2f,
                            LastName = "Simpson",
                            StudentSchoolNumber = 87654322
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
