// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemAnalysis1.Models;

#nullable disable

namespace ProblemAnalysis1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250217004535_RecreateInitial-Part-1-Part-2.1")]
    partial class RecreateInitialPart1Part21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ProblemAnalysis1.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Program");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "CP",
                            Name = "Computer Programmer"
                        },
                        new
                        {
                            Id = 2,
                            Key = "CPA",
                            Name = "Computer Programmer Analyst"
                        },
                        new
                        {
                            Id = 3,
                            Key = "BACS",
                            Name = "Bacheleor of Applied Computer Science"
                        },
                        new
                        {
                            Id = 4,
                            Key = "BCS",
                            Name = "Bacheleor of Computer Science (Honours)"
                        });
                });

            modelBuilder.Entity("ProblemAnalysis1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GPA")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentSchoolNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateofBirth = "5/31/1971",
                            FirstName = "Bart",
                            GPA = 2.7m,
                            LastName = "Simpson",
                            ProgramId = 1,
                            StudentSchoolNumber = 87654321
                        },
                        new
                        {
                            Id = 2,
                            DateofBirth = "8/5/1973",
                            FirstName = "Lisa",
                            GPA = 2.2m,
                            LastName = "Simpson",
                            ProgramId = 3,
                            StudentSchoolNumber = 87654322
                        });
                });

            modelBuilder.Entity("ProblemAnalysis1.Models.Student", b =>
                {
                    b.HasOne("ProblemAnalysis1.Models.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });
#pragma warning restore 612, 618
        }
    }
}
