// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemAnalysis1.Models;

#nullable disable

namespace ProblemAnalysis1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ProblemAnalysis1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentSchoolNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateofBirth = "1992-02-01",
                            FirstName = "Frank",
                            GPA = 3.2000000000000002,
                            LastName = "Jacob",
                            StudentSchoolNumber = 87654321
                        },
                        new
                        {
                            Id = 2,
                            DateofBirth = "1997-04-03",
                            FirstName = "Billy",
                            GPA = 2.2000000000000002,
                            LastName = "Joe",
                            StudentSchoolNumber = 87654322
                        },
                        new
                        {
                            Id = 3,
                            DateofBirth = "1991-08-02",
                            FirstName = "Timmy",
                            GPA = 1.3,
                            LastName = "Short",
                            StudentSchoolNumber = 87654323
                        },
                        new
                        {
                            Id = 4,
                            DateofBirth = "2000-04-06",
                            FirstName = "Rachel",
                            GPA = 3.2000000000000002,
                            LastName = "Blake",
                            StudentSchoolNumber = 87654324
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
